//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_cal
    {
        public int round { get; set; }
        public string item_code { get; set; }
        public int need { get; set; }
        public int circulate { get; set; }
        public int spare { get; set; }
    
        public virtual td_cal_round td_cal_round { get; set; }
    }
}
