//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_mold
    {
        public td_mold()
        {
            this.td_tran = new HashSet<td_tran>();
            this.td_reference = new HashSet<td_reference>();
        }
    
        public string mold_code { get; set; }
        public double mold_no { get; set; }
        public string item_code { get; set; }
        public int status_id { get; set; }
        public byte location_id { get; set; }
        public int cav_per_unit { get; set; }
        public byte unit_id { get; set; }
        public bool active { get; set; }
    
        public virtual tm_item tm_item { get; set; }
        public virtual tm_location tm_location { get; set; }
        public virtual tm_status tm_status { get; set; }
        public virtual tm_unit tm_unit { get; set; }
        public virtual ICollection<td_tran> td_tran { get; set; }
        public virtual ICollection<td_reference> td_reference { get; set; }
    }
}
