//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_tran
    {
        public int id { get; set; }
        public string mold_code { get; set; }
        public double mold_no { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<byte> ulv_id { get; set; }
        public Nullable<int> org_id { get; set; }
        public Nullable<byte> act_id { get; set; }
        public string actor { get; set; }
        public System.DateTime act_dt { get; set; }
        public string judge_id { get; set; }
        public string job_no { get; set; }
        public string wc { get; set; }
        public string machine { get; set; }
        public Nullable<int> shot { get; set; }
        public string status { get; set; }
        public Nullable<byte> prob_id { get; set; }
    
        public virtual td_mold td_mold { get; set; }
        public virtual tm_action tm_action { get; set; }
        public virtual tm_judgement tm_judgement { get; set; }
        public virtual tm_problem tm_problem { get; set; }
        public virtual tm_ulv tm_ulv { get; set; }
    }
}
