//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEMS1Entities : DbContext
    {
        public TEMS1Entities()
            : base("name=TEMS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_cal> td_cal { get; set; }
        public DbSet<td_cal_round> td_cal_round { get; set; }
        public DbSet<td_mold> td_mold { get; set; }
        public DbSet<td_param> td_param { get; set; }
        public DbSet<td_tran> td_tran { get; set; }
        public DbSet<tm_action> tm_action { get; set; }
        public DbSet<tm_customer> tm_customer { get; set; }
        public DbSet<tm_group> tm_group { get; set; }
        public DbSet<tm_gtype> tm_gtype { get; set; }
        public DbSet<tm_item> tm_item { get; set; }
        public DbSet<tm_judgement> tm_judgement { get; set; }
        public DbSet<tm_location> tm_location { get; set; }
        public DbSet<tm_mold> tm_mold { get; set; }
        public DbSet<tm_param> tm_param { get; set; }
        public DbSet<tm_plant> tm_plant { get; set; }
        public DbSet<tm_problem> tm_problem { get; set; }
        public DbSet<tm_product> tm_product { get; set; }
        public DbSet<tm_reference> tm_reference { get; set; }
        public DbSet<tm_status> tm_status { get; set; }
        public DbSet<tm_ulv> tm_ulv { get; set; }
        public DbSet<tm_unit> tm_unit { get; set; }
        public DbSet<tm_user> tm_user { get; set; }
        public DbSet<tm_utype> tm_utype { get; set; }
        public DbSet<tm_wc> tm_wc { get; set; }
        public DbSet<tt_mplan> tt_mplan { get; set; }
        public DbSet<v_mold_status> v_mold_status { get; set; }
        public DbSet<v_ref> v_ref { get; set; }
        public DbSet<td_reference> td_reference { get; set; }
    }
}
