//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_gtype
    {
        public tm_gtype()
        {
            this.tm_group = new HashSet<tm_group>();
        }
    
        public byte gtype_id { get; set; }
        public string gtype_name { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<tm_group> tm_group { get; set; }
    }
}
