//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_item
    {
        public tm_item()
        {
            this.td_mold = new HashSet<td_mold>();
            this.td_param = new HashSet<td_param>();
            this.tt_mplan = new HashSet<tt_mplan>();
        }
    
        public string item_code { get; set; }
        public string cust_id { get; set; }
        public string wc_id { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_mold> td_mold { get; set; }
        public virtual ICollection<td_param> td_param { get; set; }
        public virtual tm_customer tm_customer { get; set; }
        public virtual tm_wc tm_wc { get; set; }
        public virtual ICollection<tt_mplan> tt_mplan { get; set; }
    }
}
