//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_location
    {
        public tm_location()
        {
            this.td_mold = new HashSet<td_mold>();
        }
    
        public byte location_id { get; set; }
        public string location_name { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_mold> td_mold { get; set; }
    }
}
