//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_problem
    {
        public tm_problem()
        {
            this.td_tran = new HashSet<td_tran>();
            this.td_reference = new HashSet<td_reference>();
        }
    
        public byte prob_id { get; set; }
        public string prob_name { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_tran> td_tran { get; set; }
        public virtual ICollection<td_reference> td_reference { get; set; }
    }
}
