//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_param
    {
        public tm_param()
        {
            this.td_param = new HashSet<td_param>();
        }
    
        public byte param_id { get; set; }
        public string param_name { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_param> td_param { get; set; }
    }
}
