//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_reference
    {
        public tm_reference()
        {
            this.td_reference = new HashSet<td_reference>();
        }
    
        public byte ref_id { get; set; }
        public string ref_name { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_reference> td_reference { get; set; }
    }
}
