//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tooldieliveEntities : DbContext
    {
        public tooldieliveEntities()
            : base("name=tooldieliveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tr_job_progress> tr_job_progress { get; set; }
        public DbSet<tr_main_job> tr_main_job { get; set; }
        public DbSet<ts_process_result> ts_process_result { get; set; }
    }
}
