//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_mplan
    {
        public string item_code { get; set; }
        public int yy { get; set; }
        public int mm { get; set; }
        public int value { get; set; }
    
        public virtual tm_item tm_item { get; set; }
    }
}
