//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_connect_tems
    {
        public string pr_no { get; set; }
        public System.DateTime due_date { get; set; }
        public string po_no { get; set; }
        public Nullable<System.DateTime> eta_tnc { get; set; }
    }
}
