//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ref
    {
        public string mold_code { get; set; }
        public double mold_no { get; set; }
        public string ref_name { get; set; }
        public string ref_no { get; set; }
        public string prob_name { get; set; }
        public System.DateTime entry_dt { get; set; }
        public bool active { get; set; }
    }
}
